### 1 DATA WRANGLING  
      # APPROACH USED :- (WIZARD IMPORTING METHOD)
      
-- only just to edit columns i use excel because column name have space, between the columns sentence.
        
CREATE DATABASE AMAZON; -- CREATED THE DATABASE CALLED AMAZON

-- FOR IMPORT I USED WIZARD IMPORTING METHOD AND CREATED TABLE NAME CALLED AMAZON_SALES
-- LOAD THE  DATASET WHICH IS IN CSV IN MYSQL WORKBENCH.