### 2 FEATURE ENGINEERIND 

      # APPROACH USED :-
		 -- ADDING MULTIPLE NEW COLUMNS
 USE AMAZON;
 
 
ALTER TABLE AMAZON_SALES
ADD COLUMN TIME_OF_DAY VARCHAR(20);
UPDATE AMAZON_SALES
SET TIME_OF_DAY = CASE WHEN HOUR(TIME) BETWEEN 6 AND 12 THEN 'MORNING'
                  WHEN HOUR(TIME) BETWEEN 12 AND 18 THEN 'AFTERNOON'
                  ELSE 'EVENING'
                  END;           
 
ALTER TABLE AMAZON_SALES
ADD COLUMN DAY_NAME VARCHAR(20);
UPDATE AMAZON_SALES                                      -- STR_TO_DATE FUNCTION--IT WILL READ YOUR STRING(1/5/2006) CORRECTLY
SET DAY_NAME = DAYNAME(STR_TO_DATE(DATE,'%m/%d/%Y'));    -- DATA TYPE IS IN TEXT TO UNDERSTAND WE USE STR_TO_DATE FUNCTION
                                                       
 ALTER TABLE AMAZON_SALES
 ADD COLUMN MONTH_NAME VARCHAR(20);
 UPDATE AMAZON_SALES
 SET MONTH_NAME = MONTHNAME(STR_TO_DATE(DATE,'%m/%d/%Y'));
 
 SELECT * FROM AMAZON_SALES;